### ISSUE TITLE
Launch error

### ISSUE THREAD

**Issue by appsdev9** [Juanmcuello/garufa#10]
When I tried to launch garufa, I encountered the error in the attached. Please kindly help.

![g](https://user-images.githubusercontent.com/7036716/40696215-80dd49fe-63f7-11e8-82c3-383b24dce434.jpg)

**Comment by Juanmcuello** [comment]
Hi, Is this a fresh install? Could you please provide the rack version you have installed?

**Comment by Juanmcuello** [comment]
It seems there was a dependency problem. I released a new version, `1.2.1`, that should fix this issue.

**Comment by appsdev9** [comment]
Cool. Let me install it again and reply you shortly. Thanks.

2018-06-10 0:35 GMT+08:00 Juan M. Cuello <notifications@github.com>:

**Comment by appsdev9** [comment]
Hi,

You are genius. Tested OK and it really works.

May I know where I can check the garufa logs (with incoming & outgoing
messages)?

Thanks,
John


2018-06-10 17:12 GMT+08:00 John Wick <appsdev9@gmail.com>:

**Comment by Juanmcuello** [comment]
Great!

Regarding the logs, if you start Garufa with `-dv` (daemonized, verbose), logs will be generated in the same path you run the command, unless you specify a log file with `-l`. If you don't use `-d`, and use `-s` (stdout) instead, you will see all the messages in the console.
