### ISSUE TITLE
Add support for client events

### ISSUE THREAD

**Issue by Juanmcuello** [Juanmcuello/garufa#6]
Garufa does not support client-events. Would be great to support them.

See https://github.com/stevegraham/slanger/issues/220#issuecomment-254612762

/cc @dmdque

**Comment by dmdque** [comment]
Wow, thanks for adding that so quickly! Do client events require authentication the same way the Pusher backend requires it?

**Comment by Juanmcuello** [comment]
Yes, only private and presence channels are allowed. 

Take into account that for security reasons Pusher requires you to enable client events in its dashboard.  See https://pusher.com/docs/client_api_guide/client_events#trigger-events

Garufa adds this security step through a flag, so you will have to start garufa with `--enable-client-events` in order for this feature to work.

**Comment by Juanmcuello** [comment]
I released a new version (1.1.4.rc.1). You should be able to install it with `gem install garufa --pre`. Hope it works!

**Comment by dmdque** [comment]
Hey @Juanmcuello, I've installed the new version and ran it with the `--enable-client-events` flag, and I'm now able to send client events. However, I'm seeing the same issue from https://github.com/stevegraham/slanger/issues/220. I can receive the events sent from an ios client to a web client, but don't receive events from ios to ios.

It seems like this should be an ios client issue, but I've confirmed that it works when using Pusher as the backend.

**Comment by Juanmcuello** [comment]
@dmdque , I don't have an iOS device to test with, but if you provide some logs I could try to find what's going on.

You can start Garufa with `-v` flag and capture the logs when sending client events from iOS. The same thing but sending events from the web.

Also would be great to connect to the real Pusher service, configure the web client with a log function:

`Pusher.log = function(message) { console.log(message) };`

and see what is received in the JavaScript debugger console when sending events from an iOS device.

**Comment by Juanmcuello** [comment]
I'm closing this since no feedback was provided.
